import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
    return knex.raw(`
        CREATE TABLE DatabaseFiles (
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            file_name text NOT NULL,
            file_data BYTEA NOT NULL
        )
    `)
}


export async function down(knex: Knex): Promise<void> {
    return knex.raw(`
        DROP TABLE DatabaseFiles
    `);
}

