import { Injectable, NotFoundException } from '@nestjs/common';
import DatabaseService from 'src/database/database.service';
import PostgresErrorCode from 'src/database/postgres_error_code.enum';
import isRecord from 'src/utils/is_record';
import { CreateEmailUserDto } from './dto/create-email-user.dto';
import UserAlreadyExistsException from './exceptions/user_already_exists_exception.exception';
import UserModel from './models/user.model';

@Injectable()
export default class UsersRepository {
  table = 'users';
  constructor(private readonly databaseService: DatabaseService) {}

  async createEmailUser(dto: CreateEmailUserDto) {
    try {
      const emailVerified: boolean = false;
    const social: boolean = false;
    const response = await this.databaseService.runQuery(
      `
    INSERT INTO  ${this.table} ( 
        email,
        hash,
        first_name,
        last_name,
        is_social_auth,
        is_email_verified
    )

    VALUES ($1, $2,$3, $4, $5, $6)

    RETURNING *
    `,
      [
        dto.email,
        dto.password,
        dto.firstName,
        dto.lastName,
        social,
        emailVerified,
      ],
    );

    return new UserModel(response.rows[0]);
    } catch (error) {
      console.log(`Error is of type:  ${typeof error}`)
      if (isRecord(error) && error.code === PostgresErrorCode.UniqueViolation) {
        throw new UserAlreadyExistsException(dto.email);
      }
      throw error;
    }
  }

  async getUserByID(id: string) {
    const response = await this.databaseService.runQuery(
      `
     SELECT * FROM ${this.table} 
     WHERE  id = $1 
    `,
      [id],
    );
    if (!response.rows) {
      throw new NotFoundException();
    }
    return new UserModel(response.rows[0]);
  }
  async getUserByEmail(email: string) {
    const response = await this.databaseService.runQuery(
      `
     SELECT * FROM ${this.table} 
     WHERE  email = $1 
    `,
      [email],
    );
    if (!response.rows) {
      throw new NotFoundException();
    }
    return new UserModel(response.rows[0]);
  }
}

/*
import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE users (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email text UNIQUE NOT NULL,
        hash text,
        first_name text NOT NULL,
        last_name text NOT NULL,
        is_social_auth,
        is_email_verified
        
    )
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
        DROP TABLE users
    `);
}

*/