import { Injectable, NotFoundException } from '@nestjs/common';
import DatabaseService from 'src/database/database.service';
import PostgresErrorCode from 'src/database/postgres_error_code.enum';
import isRecord from 'src/utils/is_record';
import { CreateEmailUserDto } from './dto/create-email-user.dto';
import UserAlreadyExistsException from './exceptions/user_already_exists_exception.exception';
import UserModel from './models/user.model';

@Injectable()
export default class UsersRepository {
  table = 'users';
  constructor(private readonly databaseService: DatabaseService) {}

  async createEmailUser(dto: CreateEmailUserDto) {
    try {
      const emailVerified: boolean = false;
      const social: boolean = false;
      const response = await this.databaseService.runQuery(
        `
    INSERT INTO  ${this.table} ( 
        email,
        hash,
        first_name,
        last_name,
        is_social_auth,
        is_email_verified
    )

    VALUES ($1, $2,$3, $4, $5, $6)

    RETURNING *
    `,
        [
          dto.email,
          dto.password,
          dto.firstName,
          dto.lastName,
          social,
          emailVerified,
        ],
      );

      return new UserModel(response.rows[0]);
    } catch (error) {
      console.log(`Error is of type:  ${typeof error.code}`);
      // isRecord(error) &&
      if (error.code === PostgresErrorCode.UniqueViolation) {
        throw new UserAlreadyExistsException(dto.email);
      }
      throw new Error(error);
    }
  }

  async getUserByID(id: number) {
    const response = await this.databaseService.runQuery(
      `
     SELECT * FROM ${this.table} 
     WHERE  id = $1 
    `,
      [id],
    );
    if (!response.rows) {
      throw new NotFoundException();
    }
    return new UserModel(response.rows[0]);
  }
  async getUserByEmail(email: string) {
    const response = await this.databaseService.runQuery(
      `
     SELECT * FROM ${this.table} 
     WHERE  email = $1 
    `,
      [email],
    );
    if (!response.rows) {
      throw new NotFoundException();
    }
    return new UserModel(response.rows[0]);
  }

  async updatePassword(userId: number, hash: string) {
    try {
      const response = await this.databaseService.runQuery(
        `
        UPDATE ${this.table}
        SET hash = $2
        WHERE  id = $1
      `,
        [userId, hash],
      );
      console.log(response);
    } catch (error) {
      throw new Error(error);
    }
  }
  async confirmEmail() {}

  async forgotPassword() {}

  async updateAvatar(avatarId: number, userId: number) {
    const response = await this.databaseService.runQuery(
      `
      UPDATE ${this.table}
      SET avatar_id = $1
      WHERE id = $2

      RETURNING *
    `,
      [avatarId, userId],
    );
    console.log(`Error From Updating AVATAR: ${response.rows.length}`)
    if (!response.rows[0]) {
      throw new NotFoundException();
    }
    
  }
}

/*
import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE users (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email text UNIQUE NOT NULL,
        hash text,
        first_name text NOT NULL,
        last_name text NOT NULL,
        is_social_auth,
        is_email_verified
        
    )
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
        DROP TABLE users
    `);
}

*/
